#ifndef QTSFUCLIENTLIB_GLOBAL_H
#define QTSFUCLIENTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTSFUCLIENTLIB_LIBRARY)
#  define QTSFUCLIENTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTSFUCLIENTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSFUCLIENTLIB_GLOBAL_H
